import { createCanvas, GlobalFonts } from '@napi-rs/canvas';
import { writeFile } from 'node:fs/promises';
import { findMonoFont } from './runtime-paths.mjs';
// Offline development tool. No native dependency is needed to run nesterm.
const path = findMonoFont(process.argv[2] || process.env.NESTERM_FONT);
GlobalFonts.registerFromPath(path, 'GlyphMono');
function generate(height, fontSize, baseline) {
 const canvas = createCanvas(24, height), ctx = canvas.getContext('2d');
 const glyphs = [];
 for (let code = 32; code <= 126; code++) {
  ctx.fillStyle = '#000'; ctx.fillRect(0, 0, 24, height);
  ctx.fillStyle = '#fff'; ctx.font = `${fontSize}px GlyphMono`;
  ctx.textAlign = 'center'; ctx.fillText(String.fromCharCode(code), 12, baseline);
  const {data} = ctx.getImageData(0, 0, 24, height);
  const mask = [];
  for (let y=0;y<height/6;y++) for(let x=0;x<4;x++) {
    let sum=0;
    for(let dy=0;dy<6;dy++) for(let dx=0;dx<6;dx++) sum+=data[((y*6+dy)*24+x*6+dx)*4];
    mask.push(Math.round(sum/36));
  }
  glyphs.push([String.fromCharCode(code), mask]);
 }
 return glyphs;
}
await writeFile(new URL('../src/glyphs.mjs',import.meta.url), '// Generated by scripts/generate-glyphs.mjs; DejaVu Sans Mono.\nexport const GLYPHS = ' + JSON.stringify(generate(36,32,28)) + ';\nexport const GLYPHS_TALL = '+JSON.stringify(generate(48,40,37))+';\n');
console.log('Generated 95 printable ASCII glyph masks for each aspect ratio');
